"use client";
import React, { useState, useEffect, useMemo } from "react";
import Image from "next/image";
import { TextInput, Textarea, ImageUpload } from "./";
import type { SEOFields as SEOFieldsType } from "@/lib/types/seo";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { 
  AlertCircle, 
  CheckCircle, 
  Image as ImageIcon, 
  Info, 
  Link as LinkIcon, 
  Search, 
  Trash, 
  Upload 
} from "lucide-react";
import {
  generateSlug,
  generateMetaTitle,
  generateMetaDescription,
} from "@/lib/utils/dataCleaning";

export interface SEOFieldsProps {
  values: SEOFieldsType;
  onChange: (seo: SEOFieldsType, isAutoGenerated?: boolean) => void;
  firstImageUrl?: string;
  onSlugManuallyEdited?: () => void;
  onMetaTitleManuallyEdited?: () => void;
  showSectionHeader?: boolean;
  className?: string;
  errors?: {
    metaTitle?: string;
    metaDescription?: string;
    slug?: string;
    focusKeyword?: string;
    ogImage?: string;
  };
  title?: string;
  location?: string;
  shortDescription?: string;
  price?: number;
  duration?: string;
  enableAutoGeneration?: boolean;
}

const SEOFieldsComponent: React.FC<SEOFieldsProps> = ({
  values,
  onChange,
  firstImageUrl,
  onSlugManuallyEdited,
  onMetaTitleManuallyEdited,
  showSectionHeader = true,
  className = "",
  errors = {},
  title,
  location,
  shortDescription,
  price,
  duration,
  enableAutoGeneration = true,
}) => {
  const metaTitleLength = values.metaTitle?.length || 0;
  const metaDescLength = values.metaDescription?.length || 0;
  const [ogImageMode, setOgImageMode] = useState<"url" | "upload">("url");

  // "Has the user taken this field over?" — state, not refs. These flags decide
  // what the auto-generation memo below produces, so they are render inputs; a
  // ref read during render is invisible to React and would leave the memo
  // showing a stale answer until some unrelated dependency happened to change.
  const [slugManuallyEdited, setSlugManuallyEdited] = useState(false);
  const [metaTitleManuallyEdited, setMetaTitleManuallyEdited] = useState(false);
  const [metaDescriptionManuallyEdited, setMetaDescriptionManuallyEdited] =
    useState(false);

  const currentSlug = values?.slug || "";
  const currentMetaTitle = values?.metaTitle || "";
  const currentMetaDescription = values?.metaDescription || "";

  const autoGeneratedValues = useMemo(() => {
    if (!enableAutoGeneration || !title || title.trim() === "") {
      return null;
    }

    const computed: Partial<SEOFieldsType> = {};

    if (!slugManuallyEdited) {
      const autoSlug = generateSlug(title);
      if (autoSlug && autoSlug.trim() !== "") {
        computed.slug = autoSlug;
      }
    }

    if (!metaTitleManuallyEdited) {
      const autoMetaTitle = generateMetaTitle(title, location);
      if (autoMetaTitle && autoMetaTitle.trim() !== "") {
        computed.metaTitle = autoMetaTitle;
      }
    }

    if (
      shortDescription &&
      shortDescription.trim() !== "" &&
      !metaDescriptionManuallyEdited
    ) {
      const autoMetaDesc = generateMetaDescription(
        shortDescription,
        location,
        price,
        duration,
      );
      if (autoMetaDesc && autoMetaDesc.trim() !== "") {
        if (!currentMetaDescription || currentMetaDescription.trim() === "") {
          computed.metaDescription = autoMetaDesc;
        } else {
          if (currentMetaDescription === autoMetaDesc) {
            // No update needed
          } else {
            const currentStart = currentMetaDescription.substring(0, 50);
            const autoStart = autoMetaDesc.substring(0, 50);
            if (currentStart === autoStart || currentMetaDescription.length < 20) {
              computed.metaDescription = autoMetaDesc;
            }
          }
        }
      }
    }

    return Object.keys(computed).length > 0 ? computed : null;
  }, [
    enableAutoGeneration,
    title,
    location,
    shortDescription,
    price,
    duration,
    currentMetaDescription,
    slugManuallyEdited,
    metaTitleManuallyEdited,
    metaDescriptionManuallyEdited,
  ]);

  useEffect(() => {
    if (!autoGeneratedValues) return;

    let updated = false;
    const updatedValues: SEOFieldsType = {
      metaTitle: values.metaTitle ?? "",
      metaDescription: values.metaDescription ?? "",
      slug: values.slug ?? "",
      focusKeyword: values.focusKeyword ?? "",
      ogImage: values.ogImage ?? "",
    };

    if (
      autoGeneratedValues.slug !== undefined &&
      (!currentSlug || currentSlug.trim() === "" || currentSlug !== autoGeneratedValues.slug)
    ) {
      updatedValues.slug = autoGeneratedValues.slug;
      updated = true;
    }

    if (
      autoGeneratedValues.metaTitle !== undefined &&
      (!currentMetaTitle || currentMetaTitle.trim() === "" || currentMetaTitle !== autoGeneratedValues.metaTitle)
    ) {
      updatedValues.metaTitle = autoGeneratedValues.metaTitle;
      updated = true;
    }

    if (
      !metaDescriptionManuallyEdited &&
      autoGeneratedValues.metaDescription !== undefined &&
      (!currentMetaDescription || currentMetaDescription.trim() === "" || currentMetaDescription !== autoGeneratedValues.metaDescription)
    ) {
      updatedValues.metaDescription = autoGeneratedValues.metaDescription;
      updated = true;
    }

    if (updated) {
      onChange(updatedValues, true);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [
    autoGeneratedValues,
    currentSlug,
    currentMetaTitle,
    currentMetaDescription,
    values.focusKeyword,
    values.ogImage,
  ]);

  const handleFieldChange = (field: keyof SEOFieldsType, value: string) => {
    onChange({
      metaTitle: values.metaTitle ?? "",
      metaDescription: values.metaDescription ?? "",
      slug: values.slug ?? "",
      focusKeyword: values.focusKeyword ?? "",
      ogImage: values.ogImage ?? "",
      [field]: value,
    });
  };

  const handleSlugChange = (value: string) => {
    setSlugManuallyEdited(true);
    if (onSlugManuallyEdited) {
      onSlugManuallyEdited();
    }

    const slug = value
      .toLowerCase()
      .trim()
      .replace(/[^a-z0-9-]/g, "-")
      .replace(/-+/g, "-")
      .replace(/^-+|-+$/g, "");

    handleFieldChange("slug", slug);
  };

  const handleMetaTitleChange = (value: string) => {
    if (value !== (values.metaTitle || "")) {
      setMetaTitleManuallyEdited(true);
      if (onMetaTitleManuallyEdited) {
        onMetaTitleManuallyEdited();
      }
    }

    handleFieldChange("metaTitle", value);
  };

  const handleSetFirstImage = () => {
    if (firstImageUrl) {
      handleFieldChange("ogImage", firstImageUrl);
      setOgImageMode("url");
    }
  };

  const handleOgImageUpload = (images: string[]) => {
    if (images.length > 0) {
      handleFieldChange("ogImage", images[0]);
      setOgImageMode("url");
    } else {
      handleFieldChange("ogImage", "");
    }
  };

  const handleRemoveOgImage = () => {
    handleFieldChange("ogImage", "");
  };

  return (
    <div className={cn("flex flex-col gap-6", className)}>
      {showSectionHeader && (
        <div className="flex flex-col gap-1 mb-2">
          <h3 className="text-lg font-semibold text-gray-900 flex items-center gap-2">
            <Search className="h-5 w-5 text-gray-500" /> SEO Settings
          </h3>
          <p className="text-sm text-gray-500">
            Optimize your content for search engines and social media sharing
          </p>
        </div>
      )}

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="flex flex-col gap-1.5">
          <TextInput
            label="Meta Title"
            description="Title shown in search results (50-60 characters recommended)"
            placeholder="Auto-generated from title"
            value={values.metaTitle || ""}
            onChange={handleMetaTitleChange}
            onBlur={() => {
              if (onMetaTitleManuallyEdited && values.metaTitle && values.metaTitle.trim() !== "") {
                onMetaTitleManuallyEdited();
              }
            }}
            maxLength={60}
            error={errors.metaTitle}
          />
          <div className="text-xs text-gray-500 mt-1 flex items-center gap-1">
            {metaTitleLength}/60 characters
            {metaTitleLength > 60 && (
              <span className="text-red-500 font-medium"> (Too long)</span>
            )}
            {metaTitleLength >= 50 && metaTitleLength <= 60 && (
              <span className="text-green-500 font-medium"> (Optimal)</span>
            )}
          </div>
        </div>

        <div className="flex flex-col gap-1.5">
          <TextInput
            label="URL Slug"
            description="SEO-friendly URL path (auto-generated from title)"
            placeholder="Auto-generated slug"
            value={values.slug || ""}
            onChange={handleSlugChange}
            onFocus={() => {
              if (onSlugManuallyEdited) {
                onSlugManuallyEdited();
              }
            }}
            maxLength={100}
            error={errors.slug}
          />
          <div className="text-xs text-gray-500 mt-1">
            Example: amazing-content-title-with-keywords
          </div>
        </div>

        <div className="flex flex-col gap-1.5">
          <TextInput
            label="Focus Keyword"
            description="Primary keyword for this content (optional)"
            placeholder="e.g., main keyword, secondary keyword"
            value={values.focusKeyword || ""}
            onChange={(value) => handleFieldChange("focusKeyword", value)}
            maxLength={50}
            error={errors.focusKeyword}
          />
        </div>

        <div className="flex flex-col gap-1.5">
          <Label className="text-sm font-medium text-gray-700">OG Image</Label>
          <p className="text-xs text-gray-500">
            Image for social media sharing (1200x630px recommended)
          </p>

          {/* Mode Toggle */}
          <div className="flex gap-2 mb-2 mt-1">
            <Button
              type="button"
              variant={ogImageMode === "url" ? "default" : "outline"}
              size="sm"
              onClick={() => setOgImageMode("url")}
              className="flex-1 sm:flex-none"
            >
              <LinkIcon className="h-4 w-4 mr-1" /> Enter URL
            </Button>
            <Button
              type="button"
              variant={ogImageMode === "upload" ? "default" : "outline"}
              size="sm"
              onClick={() => setOgImageMode("upload")}
              className="flex-1 sm:flex-none"
            >
              <Upload className="h-4 w-4 mr-1" /> Upload Image
            </Button>
          </div>

          {/* URL Input Mode */}
          {ogImageMode === "url" && (
            <div className="flex flex-col gap-2 w-full">
              <TextInput
                label=""
                placeholder="Enter image URL or paste base64 data URL"
                value={values.ogImage || ""}
                onChange={(value) => handleFieldChange("ogImage", value)}
                error={errors.ogImage}
              />
              <div className="flex gap-2 flex-wrap">
                {firstImageUrl && (
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={handleSetFirstImage}
                  >
                    <ImageIcon className="h-4 w-4 mr-1" /> Use First Image
                  </Button>
                )}
                {values.ogImage && (
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={handleRemoveOgImage}
                    className="text-red-500 hover:text-red-600 hover:bg-red-50"
                  >
                    <Trash className="h-4 w-4 mr-1" /> Clear
                  </Button>
                )}
              </div>
            </div>
          )}

          {/* Upload Mode */}
          {ogImageMode === "upload" && (
            <div className="w-full">
              <ImageUpload
                label=""
                description="Upload an image for social media sharing"
                value={values.ogImage ? [values.ogImage] : []}
                onChange={handleOgImageUpload}
                maxFiles={1}
                maxSize={5}
                multiple={false}
                acceptedTypes={["image/jpeg", "image/png", "image/webp"]}
              />
            </div>
          )}

          {/* Image Preview */}
          {values.ogImage && (
            <div className="mt-2">
              <Label className="text-xs font-medium text-gray-700">Preview</Label>
              <div className="border border-gray-200 rounded-lg p-2 inline-block bg-white mt-1">
                <Image
                  src={values.ogImage}
                  alt="OG Image Preview"
                  width={120}
                  height={120}
                  className="rounded-md object-contain w-[120px] h-[120px]"
                />
              </div>
              <div className="text-xs text-gray-500 mt-1 flex items-center gap-1">
                <Info className="h-3.5 w-3.5" /> Recommended size: 1200x630px for optimal social media display
              </div>
            </div>
          )}

          {errors.ogImage && (
            <p className="text-sm text-red-500 flex items-center gap-1 mt-0.5">
              <AlertCircle className="h-3.5 w-3.5" />
              {errors.ogImage}
            </p>
          )}
        </div>
      </div>

      <div className="flex flex-col gap-1.5">
        <Textarea
          label="Meta Description"
          description="Description shown in search results (150-160 characters recommended)"
          placeholder="Auto-generated from short description"
          value={values.metaDescription || ""}
          onChange={(value) => {
            const currentValue = values.metaDescription || "";
            const isSignificantChange =
              value.length > 1 || 
              (currentValue.length > 10 && value.length < currentValue.length - 5);

            if (isSignificantChange && value !== currentValue) {
              setMetaDescriptionManuallyEdited(true);
            }
            handleFieldChange("metaDescription", value);
          }}
          rows={3}
          maxLength={160}
          showCharCount
          error={errors.metaDescription}
        />
        <div className="text-xs text-gray-500 mt-1 flex items-center gap-1">
          {metaDescLength >= 150 && metaDescLength <= 160 && (
            <span className="text-green-500 flex items-center gap-1 font-medium">
              <CheckCircle className="h-3.5 w-3.5" /> Optimal length
            </span>
          )}
          {metaDescLength < 120 && (
            <span className="text-yellow-500 flex items-center gap-1 font-medium">
              <AlertCircle className="h-3.5 w-3.5" /> Consider adding more details
            </span>
          )}
        </div>
      </div>
    </div>
  );
};

const SEOFields = SEOFieldsComponent;
export default SEOFields;
