"use client";
import React, { useState, useEffect, useRef, useMemo } from "react";
import { TextInput, Textarea, ImageUpload } from "./";
import type { SEOFields } from "@/lib/types/seo";
import Image from "next/image";
import {
  generateSlug,
  generateMetaTitle,
  generateMetaDescription,
} from "@/lib/utils/dataCleaning";
import { Group } from "../Common";

export interface SEOFieldsProps {
  /**
   * Current SEO field values
   */
  values: SEOFields;
  /**
   * Callback when any SEO field changes
   */
  onChange: (seo: SEOFields) => void;
  /**
   * Optional: First image URL for auto-setting OG Image
   */
  firstImageUrl?: string;
  /**
   * Optional: Callback when slug is manually edited (to prevent auto-generation)
   */
  onSlugManuallyEdited?: () => void;
  /**
   * Optional: Callback when meta title is manually edited (to prevent auto-generation)
   */
  onMetaTitleManuallyEdited?: () => void;
  /**
   * Optional: Whether to show section header
   */
  showSectionHeader?: boolean;
  /**
   * Optional: Custom className
   */
  className?: string;
  /**
   * Optional: Error messages for each field
   */
  errors?: {
    metaTitle?: string;
    metaDescription?: string;
    slug?: string;
    focusKeyword?: string;
    ogImage?: string;
  };
  /**
   * Optional: Content title for auto-generating slug and meta title
   */
  title?: string;
  /**
   * Optional: Content location/context for auto-generating meta title and description
   */
  location?: string;
  /**
   * Optional: Short description for auto-generating meta description
   */
  shortDescription?: string;
  /**
   * Optional: Price/value for auto-generating meta description
   */
  price?: number;
  /**
   * Optional: Duration/timeframe for auto-generating meta description
   */
  duration?: string;
  /**
   * Optional: Enable auto-generation (default: true)
   */
  enableAutoGeneration?: boolean;
}

/**
 * Reusable SEO Fields Component
 *
 * This component provides a complete SEO form section with:
 * - Meta Title (with character counter)
 * - URL Slug (with auto-generation support)
 * - Focus Keyword
 * - OG Image URL (with quick-set button)
 * - Meta Description (with character counter)
 */
const SEOFields: React.FC<SEOFieldsProps> = ({
  values,
  onChange,
  firstImageUrl,
  onSlugManuallyEdited,
  onMetaTitleManuallyEdited,
  showSectionHeader = true,
  className = "",
  errors = {},
  title,
  location,
  shortDescription,
  price,
  duration,
  enableAutoGeneration = true,
}) => {
  const metaTitleLength = values.metaTitle?.length || 0;
  const metaDescLength = values.metaDescription?.length || 0;
  const [ogImageMode, setOgImageMode] = useState<"url" | "upload">("url");

  // Track manual edits to prevent auto-generation from overwriting user input
  const slugManuallyEditedRef = useRef(false);
  const metaTitleManuallyEditedRef = useRef(false);

  // Extract only the fields we need to check
  const currentSlug = values?.slug || "";
  const currentMetaTitle = values?.metaTitle || "";
  const currentMetaDescription = values?.metaDescription || "";

  // Compute auto-generated values only when source fields change (not on every render)
  const autoGeneratedValues = useMemo(() => {
    if (!enableAutoGeneration || !title || title.trim() === "") {
      return null;
    }

    const computed: Partial<SEOFields> = {};

    // Only compute slug if user hasn't manually edited it
    if (!slugManuallyEditedRef.current) {
      const autoSlug = generateSlug(title);
      if (autoSlug && autoSlug.trim() !== "") {
        computed.slug = autoSlug;
      }
    }

    // Only compute meta title if user hasn't manually edited it
    if (!metaTitleManuallyEditedRef.current) {
      const autoMetaTitle = generateMetaTitle(title, location);
      if (autoMetaTitle && autoMetaTitle.trim() !== "") {
        computed.metaTitle = autoMetaTitle;
      }
    }

    // Only compute meta description if empty
    if (
      shortDescription &&
      (!currentMetaDescription || currentMetaDescription.trim() === "")
    ) {
      const autoMetaDesc = generateMetaDescription(
        shortDescription,
        location,
        price,
        duration
      );
      if (autoMetaDesc && autoMetaDesc.trim() !== "") {
        computed.metaDescription = autoMetaDesc;
      }
    }

    return Object.keys(computed).length > 0 ? computed : null;
  }, [
    enableAutoGeneration,
    title,
    location,
    shortDescription,
    price,
    duration,
    currentMetaDescription, // Only check if meta description is empty
  ]);

  // Sync computed values only when they change and differ from current values
  useEffect(() => {
    if (!autoGeneratedValues) return;

    let updated = false;
    const updatedValues = { ...values };

    // Update slug if computed and different
    if (
      autoGeneratedValues.slug !== undefined &&
      (!currentSlug ||
        currentSlug.trim() === "" ||
        currentSlug !== autoGeneratedValues.slug)
    ) {
      updatedValues.slug = autoGeneratedValues.slug;
      updated = true;
    }

    // Update meta title if computed and different
    if (
      autoGeneratedValues.metaTitle !== undefined &&
      (!currentMetaTitle ||
        currentMetaTitle.trim() === "" ||
        currentMetaTitle !== autoGeneratedValues.metaTitle)
    ) {
      updatedValues.metaTitle = autoGeneratedValues.metaTitle;
      updated = true;
    }

    // Update meta description if computed and different
    if (
      autoGeneratedValues.metaDescription !== undefined &&
      (!currentMetaDescription ||
        currentMetaDescription.trim() === "" ||
        currentMetaDescription !== autoGeneratedValues.metaDescription)
    ) {
      updatedValues.metaDescription = autoGeneratedValues.metaDescription;
      updated = true;
    }

    // Only call onChange if something actually changed
    if (updated) {
      onChange(updatedValues);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [
    autoGeneratedValues,
    currentSlug,
    currentMetaTitle,
    currentMetaDescription,
  ]);

  const handleFieldChange = (field: keyof SEOFields, value: string) => {
    onChange({
      ...values,
      [field]: value,
    });
  };

  const handleSlugChange = (value: string) => {
    // Mark as manually edited
    slugManuallyEditedRef.current = true;
    if (onSlugManuallyEdited) {
      onSlugManuallyEdited();
    }

    // Clean the slug input
    const slug = value
      .toLowerCase()
      .trim()
      .replace(/[^a-z0-9-]/g, "-")
      .replace(/-+/g, "-")
      .replace(/^-+|-+$/g, "");

    handleFieldChange("slug", slug);
  };

  const handleMetaTitleChange = (value: string) => {
    // Mark as manually edited only when user actually changes the value
    if (value !== (values.metaTitle || "")) {
      metaTitleManuallyEditedRef.current = true;
      if (onMetaTitleManuallyEdited) {
        onMetaTitleManuallyEdited();
      }
    }

    handleFieldChange("metaTitle", value);
  };

  const handleSetFirstImage = () => {
    if (firstImageUrl) {
      handleFieldChange("ogImage", firstImageUrl);
      setOgImageMode("url");
    } else {
      console.warn("No first image URL provided");
    }
  };

  const handleOgImageUpload = (images: string[]) => {
    if (images.length > 0) {
      handleFieldChange("ogImage", images[0]);
      // Switch to URL mode after upload to show the preview
      setOgImageMode("url");
    } else {
      handleFieldChange("ogImage", "");
    }
  };

  const handleRemoveOgImage = () => {
    handleFieldChange("ogImage", "");
  };

  return (
    <div className={`form-section ${className}`}>
      {showSectionHeader && (
        <div className="section-header">
          <h3>
            <i className="bi bi-search"></i> SEO Settings
          </h3>
          <p className="section-description">
            Optimize your content for search engines and social media sharing
          </p>
        </div>
      )}

      <div className="form-grid">
        <div className="form-group">
          <TextInput
            label="Meta Title"
            description="Title shown in search results (50-60 characters recommended)"
            placeholder="Auto-generated from title"
            value={values.metaTitle || ""}
            onChange={handleMetaTitleChange}
            onBlur={() => {
              // Mark as manually edited when user leaves the field after editing
              if (
                onMetaTitleManuallyEdited &&
                values.metaTitle &&
                values.metaTitle.trim() !== ""
              ) {
                onMetaTitleManuallyEdited();
              }
            }}
            maxLength={60}
            error={errors.metaTitle}
          />
          <div className="form-helper-text">
            {metaTitleLength}/60 characters
            {metaTitleLength > 60 && (
              <span className="text-danger"> (Too long)</span>
            )}
            {metaTitleLength >= 50 && metaTitleLength <= 60 && (
              <span className="text-success"> (Optimal)</span>
            )}
          </div>
        </div>

        <div className="form-group">
          <TextInput
            label="URL Slug"
            description="SEO-friendly URL path (auto-generated from title)"
            placeholder="Auto-generated slug"
            value={values.slug || ""}
            onChange={handleSlugChange}
            onFocus={() => {
              // Mark as manually edited when user focuses on the field
              if (onSlugManuallyEdited) {
                onSlugManuallyEdited();
              }
            }}
            maxLength={100}
            error={errors.slug}
          />
          <div className="form-helper-text">
            Example: amazing-content-title-with-keywords
          </div>
        </div>

        <div className="form-group">
          <TextInput
            label="Focus Keyword"
            description="Primary keyword for this content (optional)"
            placeholder="e.g., main keyword, secondary keyword"
            value={values.focusKeyword || ""}
            onChange={(value) => handleFieldChange("focusKeyword", value)}
            maxLength={50}
            error={errors.focusKeyword}
          />
        </div>

        <div className="form-group">
          <label className="form-label">OG Image</label>
          <p className="form-description">
            Image for social media sharing (1200x630px recommended)
          </p>

          {/* Mode Toggle */}
          <div
            className="d-flex gap-2 mb-3"
            role="group"
            style={{
              flexWrap: "wrap",
              display: "flex",
              width: "100%",
              marginBottom: "1rem",
            }}
          >
            <button
              type="button"
              className={`btn btn-sm ${
                ogImageMode === "url" ? "btn-primary" : "btn-outline-primary"
              }`}
              onClick={(e) => {
                e.preventDefault();
                e.stopPropagation();
                setOgImageMode("url");
              }}
              style={{
                display: "inline-flex",
                alignItems: "center",
                gap: "0.5rem",
                minWidth: "120px",
                justifyContent: "center",
              }}
            >
              <i className="bi bi-link-45deg"></i> Enter URL
            </button>
            <button
              type="button"
              className={`btn btn-sm ${
                ogImageMode === "upload" ? "btn-primary" : "btn-outline-primary"
              }`}
              onClick={(e) => {
                e.preventDefault();
                e.stopPropagation();
                setOgImageMode("upload");
              }}
              style={{
                display: "inline-flex",
                alignItems: "center",
                gap: "0.5rem",
                minWidth: "120px",
                justifyContent: "center",
              }}
            >
              <i className="bi bi-upload"></i> Upload Image
            </button>
          </div>

          {/* URL Input Mode */}
          <div
            style={{
              width: "100%",
              display: ogImageMode === "url" ? "block" : "none",
            }}
          >
            <TextInput
              label=""
              placeholder="Enter image URL or paste base64 data URL"
              value={values.ogImage || ""}
              onChange={(value) => handleFieldChange("ogImage", value)}
              error={errors.ogImage}
            />
            <div
              className="d-flex gap-2 mt-2"
              style={{ display: "flex", flexWrap: "wrap", width: "100%" }}
            >
              {firstImageUrl && (
                <button
                  type="button"
                  className="btn btn-sm btn-outline-primary"
                  onClick={(e) => {
                    e.preventDefault();
                    e.stopPropagation();
                    handleSetFirstImage();
                  }}
                  style={{
                    display: "inline-flex",
                    alignItems: "center",
                    gap: "0.5rem",
                  }}
                >
                  <i className="bi bi-image"></i> Use First Image
                </button>
              )}
              {values.ogImage && (
                <button
                  type="button"
                  className="btn btn-sm btn-outline-danger"
                  onClick={(e) => {
                    e.preventDefault();
                    e.stopPropagation();
                    handleRemoveOgImage();
                  }}
                  style={{
                    display: "inline-flex",
                    alignItems: "center",
                    gap: "0.5rem",
                  }}
                >
                  <i className="bi bi-trash"></i> Clear
                </button>
              )}
            </div>
          </div>

          {/* Upload Mode */}
          <div
            style={{
              width: "100%",
              display: ogImageMode === "upload" ? "block" : "none",
            }}
          >
            <ImageUpload
              label=""
              description="Upload an image for social media sharing"
              value={values.ogImage ? [values.ogImage] : []}
              onChange={handleOgImageUpload}
              maxFiles={1}
              maxSize={5}
              multiple={false}
              acceptedTypes={["image/jpeg", "image/png", "image/webp"]}
            />
          </div>

          {/* Image Preview */}
          {values.ogImage && (
            <div className="mt-3">
              <label className="form-label">Preview</label>
              <div
                className="border rounded p-2"
                style={{
                  display: "inline-block",
                  maxWidth: "100%",
                }}
              >
                <Image
                  src={values.ogImage}
                  alt="OG Image Preview"
                  width={120}
                  height={120}
                  style={{
                    width: "120px",
                    height: "120px",
                    objectFit: "contain",
                  }}
                  className="rounded"
                />
              </div>
              <div className="form-helper-text mt-1">
                <i className="bi bi-info-circle"></i> Recommended size:
                1200x630px for optimal social media display
              </div>
            </div>
          )}

          {errors.ogImage && (
            <p className="form-error mt-2">
              <i className="bi bi-exclamation-circle form-error-icon"></i>
              {errors.ogImage}
            </p>
          )}
        </div>
      </div>

      <div className="form-group">
        <Textarea
          label="Meta Description"
          description="Description shown in search results (150-160 characters recommended)"
          placeholder="Auto-generated from short description"
          value={values.metaDescription || ""}
          onChange={(value) => handleFieldChange("metaDescription", value)}
          rows={3}
          maxLength={160}
          showCharCount
          error={errors.metaDescription}
        />
        <div className="form-helper-text mt-1">
          {metaDescLength >= 150 && metaDescLength <= 160 && (
            <span className="text-success">
              <i className="bi bi-check-circle"></i> Optimal length
            </span>
          )}
          {metaDescLength < 120 && (
            <span className="text-warning">
              <i className="bi bi-exclamation-triangle"></i> Consider adding
              more details
            </span>
          )}
        </div>
      </div>
    </div>
  );
};

export default SEOFields;
